version: "3.9"

services:
  db:
    image: kleytondev/msn-db:latest
    environment:
      - MYSQL_DATABASE=msn
      - MYSQL_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_ROOT_PASSWORD=
    ports:
      - '3307:3306'
    volumes:
      - ./msn-db:/var/lib/mysql
