version: "3.9"

services:
#  PHP service
  php:
    build:
      context: .
      target: php
      args:
        - APP_ENV=${APP_ENV}
    environment:
      - APP_ENV=${APP_ENV}
      - CONTAINER_ROLE=app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db

  # Db Sercice
  db:
    image: kleytondev/msn-db:latest
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_ROOT_PASSWORD=
    ports:
      - '3307:3306'
    volumes:
      - ./msn-db:/var/lib/mysql
  cache:
      image: redis:6.2-alpine
      restart: always
      ports:
          - '6380:6379'
      environment:
        REDIS_HOST: cache
        REDIS_PORT: 6379
        REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      volumes:
          - ./cache:/data
